# This is a basic workflow that is manually triggered

name : 01-first-input-workflow

#controls when the action will run. Workflow runs when manually triggred using UI
#or API

on:
  workflow_dispatch:
    #friendly description to be shown in the UI instead of 'name'
    inputs:
      name:
        #Friendly description to be shown in the UI instead of 'name'
        description: 'person to greet'
        #Default value if no value is explicitily provided
        default: 'world'
        #Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in pararllel
jobs:
  # This workflow contains a single job called 'greet'
  greet:
    #The  type of runner that the job will run on
      runs-on: ubuntu-latest

      #steps represent a sequence of tasks that will be executed as part of the job

      steps:
       #Runs a singe command using the runner shell
       - name: send greeting
         run: echo "Hello ${{github.event.input.name }}"
         
